apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-api
  namespace: mvp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
        - name: ecommerce-api
          image: 336061352830.dkr.ecr.us-east-1.amazonaws.com/event-driven-ecommerce-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ecommerce-api-env