apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: mvp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
        - name: ecommerce-frontend
          image: 336061352830.dkr.ecr.us-east-1.amazonaws.com/event-driven-ecommerce-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://ecommerce-api-service/api/v1"