apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: mvp
spec:
  selector:
    app: ecommerce-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer